version: '3'

services:
  neo4j:
    image: neo4j
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/senacsenac
    volumes:
      - /neo4j-data:/data
    networks:
      - neo4j-network

networks:
  neo4j-network:
